# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 60984fdc20801b436cf62250259e906ec9056ad5aee469924a9a98bb63ea952393fc2ba20dfc8a4ccd5048a5a872364631243c790e797122e5e8fb5920c34d04

test:
  secret_key_base: b92728982d010483681ad05694d6e17fa7487fde8014e677f46e6a6347b7110f23532f7276e01e2cd46a9409de8a739264edf0c6a2af6f920f0bca4216bcf0dd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
